name: Apt based Linux
on:
  push:
  pull_request:
jobs:
  test:
    name: Test ${{ matrix.label }} ${{ matrix.test }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        label:
          - Debian bullseye amd64
          - Ubuntu Focal amd64
          - Ubuntu Jammy amd64
        test:
          - "update-from-v4.sh"
        include:
          - label: Debian bullseye amd64
            rake-job: debian-bullseye
            lxc-image: images:debian/11
          - label: Ubuntu Focal amd64
            rake-job: ubuntu-focal
            lxc-image: ubuntu:20.04
          - label: Ubuntu Jammy amd64
            rake-job: ubuntu-jammy
            lxc-image: ubuntu:22.04
    steps:
      - uses: actions/checkout@master
      - uses: canonical/setup-lxd@v0.1.1
      - name: Run Test  ${{ matrix.test }} on ${{ matrix.lxc-image }}
        run: fluent-package/apt/systemd-test/test.sh ${{ matrix.lxc-image }} ${{ matrix.test }}
