name: Apt based Linux
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        label:
          - Debian bullseye amd64
          - Ubuntu Focal amd64
        include:
          - label: Debian bullseye amd64
            rake-job: debian-bullseye
            test-docker-image: debian:bullseye
          - label: Ubuntu Focal amd64
            rake-job: ubuntu-focal
            test-docker-image: ubuntu:focal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby ruby-bundler ruby-serverspec
          sudo gem install bundler:2.2.9 --no-document
          sudo gem uninstall fileutils
      - name: cache deb
        uses: actions/cache@v4
        id: cache-deb
        with:
          path: |
            fluent-package/apt/repositories
            fluent-apt-source/apt/repositories
            fluent-lts-apt-source/apt/repositories
          key: ${{ runner.os }}-cache-${{ matrix.rake-job }}-${{ hashFiles('**/config.rb', '**/Rakefile', '**/Gemfile*', 'fluent-package/templates/**', 'fluent-package/debian/**', 'fluent-package/apt/**/Dockerfile') }}
      - name: Build deb with Docker
        if: ${{ ! steps.cache-deb.outputs.cache-hit }}
        run: |
          rake apt:build APT_TARGETS=${{ matrix.rake-job }}
      - name: Upload fluent-package deb
        uses: actions/upload-artifact@master
        with:
          name: packages-${{ matrix.rake-job }}
          path: fluent-package/apt/repositories
      - name: Upload fluent-apt-source deb
        uses: actions/upload-artifact@master
        with:
          name: packages-apt-source-${{ matrix.rake-job }}
          path: fluent-apt-source/apt/repositories
      - name: Upload fluent-lts-apt-source deb
        uses: actions/upload-artifact@master
        with:
          name: packages-lts-apt-source-${{ matrix.rake-job }}
          path: fluent-lts-apt-source/apt/repositories
  test:
    name: Test ${{ matrix.label }} ${{ matrix.test }}
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        label:
          - Debian bullseye amd64
          - Ubuntu Focal amd64
        test:
          - "update-from-v4.sh local"
          - "update-from-v4.sh v5"
          - "update-from-v4.sh lts"
        include:
          - label: Debian bullseye amd64
            rake-job: debian-bullseye
            lxc-image: images:debian/11
          - label: Ubuntu Focal amd64
            rake-job: ubuntu-focal
            lxc-image: ubuntu:20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v4
        with:
          name: packages-${{ matrix.rake-job }}
      - uses: actions/download-artifact@v4
        with:
          name: packages-apt-source-${{ matrix.rake-job }}
      - uses: canonical/setup-lxd@v0.1.1
      - name: Run Test  ${{ matrix.test }} on ${{ matrix.lxc-image }}
        run: fluent-package/apt/systemd-test/test.sh ${{ matrix.lxc-image }} ${{ matrix.test }}
