name: Apt based Linux
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        label:
          - Debian bullseye amd64
          - Debian bookworm amd64
          - Ubuntu Focal amd64
        include:
          - label: Debian bullseye amd64
            rake-job: debian-bullseye
            test-docker-image: debian:bullseye
          - label: Debian bookworm amd64
            rake-job: debian-bookworm
            test-docker-image: debian:bookworm
          - label: Ubuntu Focal amd64
            rake-job: ubuntu-focal
            test-docker-image: ubuntu:focal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby ruby-bundler ruby-serverspec
          sudo gem install bundler:2.2.9 --no-document
          sudo gem uninstall fileutils
      - name: Build deb with Docker
        run: |
          rake apt:build APT_TARGETS=${{ matrix.rake-job }}
      - name: Upload fluent-package deb
        uses: actions/upload-artifact@master
        with:
          name: packages-${{ matrix.rake-job }}
          path: fluent-package/apt/repositories
      - name: Cache v6 dummy
        id: cache-v6-dummy
        uses: actions/cache@master
        with:
          key: fluent-package-v6-dummy ${{ matrix.label }}
          path: v6-test/fluent-package/apt/repositories
      - if: ${{ ! steps.cache-v6-dummy.outputs.cache-hit }}
        uses: actions/checkout@master
        with:
          ref: fluent-package-v6-dummy
          path: v6-test
      - if: ${{ ! steps.cache-v6-dummy.outputs.cache-hit }}
        name: Build dummy v6 deb with Docker
        run: |
          cd v6-test
          rake apt:build APT_TARGETS=${{ matrix.rake-job }}
      - name: Upload v6 fluent-package deb
        uses: actions/upload-artifact@master
        with:
          name: v6-packages-${{ matrix.rake-job }}
          path: v6-test/fluent-package/apt/repositories
      - name: Upload fluent-apt-source deb
        uses: actions/upload-artifact@master
        with:
          name: packages-apt-source-${{ matrix.rake-job }}
          path: fluent-apt-source/apt/repositories
      - name: Upload fluent-lts-apt-source deb
        uses: actions/upload-artifact@master
        with:
          name: packages-lts-apt-source-${{ matrix.rake-job }}
          path: fluent-lts-apt-source/apt/repositories
