name: macOS
on: push
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Install cmake
        run: |
          brew install cmake
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Install gems
        run: |
          gem install bundler builder
      - name: Build
        run: |
          sudo mkdir /opt/fluent
          sudo chown $(whoami) /opt/fluent
          rm -rf fluent/staging
          rake dmg:selfbuild PATH="$HOME/.cargo/bin:$PATH"
      - name: Upload td-agent dmg
        uses: actions/upload-artifact@master
        with:
          name: packages-macos
          path: fluent-package/dmg/*.dmg
