name: Yum based Linux
on:
  push:
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      label: ${{ steps.set-matrix.outputs.label }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        # See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#example-returning-a-json-object
        run: |
          echo "matrix=$(cat yum.matrix.json | jq --compact-output)" >> $GITHUB_OUTPUT
          echo "label=$(cat yum.matrix.json | jq '[.include[].label]' --compact-output)" >> $GITHUB_OUTPUT
        working-directory: .github/workflows/
  build:
    needs: define-matrix
    name: Build
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cache rpm
        uses: actions/cache@v4
        id: cache-rpm
        with:
          path: |
            fluent-package/yum/repositories
            fluent-release/yum/repositories
            fluent-lts-release/yum/repositories
            v7-test/fluent-package/yum/repositories
          key: ${{ runner.os }}-cache-${{ matrix.rake-job }}-${{ hashFiles('**/config.rb', '**/Rakefile', '**/Gemfile*', '**/*.spec.in', 'fluent-package/templates/**', 'fluent-package/yum/**/Dockerfile') }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
      - name: Install dependencies
        if: ${{ ! steps.cache-rpm.outputs.cache-hit }}
        run: |
          gem install serverspec --no-document
      - name: Build rpm with Docker
        if: ${{ ! steps.cache-rpm.outputs.cache-hit }}
        run: |
          rake yum:build YUM_TARGETS=${{ matrix.rake-job }}
      - uses: actions/checkout@v4
        if: ${{ ! steps.cache-rpm.outputs.cache-hit }}
        with:
          path: v7-test
      - name: Build v7 rpm with Docker
        if: ${{ ! steps.cache-rpm.outputs.cache-hit }}
        run: |
          cd v7-test
          git config user.email "fluentd@googlegroups.com"
          git config user.name "Fluentd developers"
          git am fluent-package/bump-version-v7.patch
          rake yum:build YUM_TARGETS=${{ matrix.rake-job }}
      - name: Upload fluent-package rpm
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.rake-job }}
          path: fluent-package/yum/repositories
      - name: Upload fluent-release rpm
        uses: actions/upload-artifact@v4
        with:
          name: packages-release-${{ matrix.rake-job }}
          path: fluent-release/yum/repositories
      - name: Upload fluent-lts-release rpm
        uses: actions/upload-artifact@v4
        with:
          name: packages-lts-release-${{ matrix.rake-job }}
          path: fluent-lts-release/yum/repositories
      - name: Upload v7 fluent-package rpm
        uses: actions/upload-artifact@v4
        with:
          name: v7-packages-${{ matrix.rake-job }}
          path: v7-test/fluent-package/yum/repositories

  v2test:
    name: Test ${{ matrix.label }} ${{ matrix.test }} (CGroup V2)
    needs: [define-matrix, build]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        label: ${{ fromJSON(needs.define-matrix.outputs.label) }}
        test:
          - "tmpfiles.sh"
        include: ${{ fromJSON(needs.define-matrix.outputs.matrix).include }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: packages-${{ matrix.rake-job }}
      - uses: actions/download-artifact@v4
        with:
          name: packages-release-${{ matrix.rake-job }}
      - uses: actions/download-artifact@v4
        with:
          name: v7-packages-${{ matrix.rake-job }}
          path: v7-test
      - name: Install Incus
        run: |
          sudo apt-get update
          sudo apt-get install -y -V incus
      - name: Allow egress network traffic flows for Incus
        # https://linuxcontainers.org/incus/docs/main/howto/network_bridge_firewalld/#prevent-connectivity-issues-with-incus-and-docker
        run: |
          sudo iptables -I DOCKER-USER -i incusbr0 -j ACCEPT
          sudo iptables -I DOCKER-USER -o incusbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      - name: Setup Incus
        run: |
          sudo incus admin init --auto
      - name: Run Test ${{ matrix.test }} on ${{ matrix.test-incus-image }}
        run: fluent-package/yum/systemd-test/test.sh ${{ matrix.test-incus-image }} ${{ matrix.test }}
