name: Yum based Linux
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        label:
          - CentOS 7 x86_64
          - RockyLinux 8 x86_64
          - AlmaLinux 9 x86_64
          - Amazon Linux 2 x86_64
          - Amazon Linux 2023 x86_64
        include:
          - label: CentOS 7 x86_64
            rake-job: centos-7
            test-docker-image: centos:7
            centos-stream: false
          - label: RockyLinux 8 x86_64
            rake-job: rockylinux-8
            test-docker-image: rockylinux/rockylinux:8
            centos-stream: false
          - label: AlmaLinux 9 x86_64
            rake-job: almalinux-9
            test-docker-image: almalinux:9
            centos-stream: false
          - label: Amazon Linux 2 x86_64
            rake-job: amazonlinux-2
            test-docker-image: amazonlinux:2
            centos-stream: false
          - label: Amazon Linux 2023 x86_64
            rake-job: amazonlinux-2023
            test-docker-image: amazonlinux:2023
            centos-stream: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby ruby-bundler ruby-serverspec
          sudo gem install bundler:2.2.9 --no-document
          sudo gem uninstall fileutils
      - name: Build rpm with Docker
        run: |
          rake yum:build YUM_TARGETS=${{ matrix.rake-job }}
      - name: Upload fluent-package rpm
        uses: actions/upload-artifact@master
        with:
          name: packages-${{ matrix.rake-job }}
          path: fluent-package/yum/repositories
      # TODO move the following steps to "Test" job
      - name: Check Package Size
        run: |
          fluent-package/yum/pkgsize-test.sh ${{ matrix.rake-job }} x86_64
      - name: Installation Test
        run: |
          mkdir -p .bundle
          docker run \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          --env CENTOS_STREAM=${{ matrix.centos-stream }} \
          ${{ matrix.test-docker-image }} \
          /fluentd/fluent-package/yum/install-test.sh
      - name: Binstubs Test
        run: |
          mkdir -p .bundle
          docker run \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          --env CENTOS_STREAM=${{ matrix.centos-stream }} \
          ${{ matrix.test-docker-image }} \
          /fluentd/fluent-package/yum/binstubs-test.sh
  test:
    name: Test
    needs: build
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - centos-7
          - rockylinux-8
          - almalinux-9
          - amazonlinux-2
          # - amazonlinux-2023
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: packages-${{ matrix.distribution }}
      - name: Run Test
        run: fluent-package/yum/systemd-test/test.sh ${{ matrix.distribution }}
