name: Yum based Linux
on:
  push:
  pull_request:
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        label:
          - RockyLinux 8 x86_64
          - AlmaLinux 9 x86_64
        include:
          - label: RockyLinux 8 x86_64
            rake-job: rockylinux-8
            test-docker-image: rockylinux:8
            centos-stream: false
          - label: AlmaLinux 9 x86_64
            rake-job: almalinux-9
            test-docker-image: almalinux:9
            centos-stream: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby ruby-bundler ruby-serverspec
          sudo gem install bundler:2.2.9 --no-document
          sudo gem uninstall fileutils
      - name: Build rpm with Docker
        run: |
          rake yum:build YUM_TARGETS=${{ matrix.rake-job }}
      - name: Upload fluent-package rpm
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.rake-job }}
          path: fluent-package/yum/repositories

  v2test:
    name: Test ${{ matrix.label }} ${{ matrix.test }} (CGroup V2)
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        label:
          - RockyLinux 8 x86_64
          - AlmaLinux 9 x86_64
        test:
          - "update-from-v4.sh"
          - "downgrade-to-v4.sh"
          - "install-newly.sh local"
          - "install-newly.sh v5"
          - "install-newly.sh lts"
          - "update-to-next-version.sh"
          - "update-to-next-version-with-backward-compat-for-v4.sh"
          - "update-to-next-version-service-status.sh enabled active"
          - "update-to-next-version-service-status.sh enabled inactive"
          - "update-to-next-version-service-status.sh disabled active"
          - "update-to-next-version-service-status.sh disabled inactive"
        include:
          - label: RockyLinux 8 x86_64
            rake-job: rockylinux-8
            lxc-image: images:rockylinux/8
          - label: AlmaLinux 9 x86_64
            rake-job: almalinux-9
            lxc-image: images:almalinux/9
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v4
        with:
          name: packages-${{ matrix.rake-job }}
      - uses: canonical/setup-lxd@v0.1.1
      - name: Run Test ${{ matrix.test }} on ${{ matrix.lxc-image }}
        run: fluent-package/yum/systemd-test/test.sh ${{ matrix.lxc-image }} ${{ matrix.test }}
